import { Layout } from '@/components/Layout'
import { LoginModal } from '@/components/Modals/LoginModal'
import { RegisterModal } from '@/components/Modals/RegisterModal'
import { Provider } from '@/components/Providers'
import { Roboto } from 'next/font/google'
import { ReactNode } from 'react'

import './globals.css'

const roboto = Roboto({
   weight: '500',
   subsets: ['latin'],
   display: 'swap',
})

export const metadata = {
   title: 'Página inicial / Twitter Clone',
   description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
   return (
      <html lang="pt-br">
         <body className={roboto.className}>
            <Provider>
               <LoginModal />
               <RegisterModal />
               <Layout>{children}</Layout>
            </Provider>
         </body>
      </html>
   )
}
